[project]
name = "uv2nix"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  'requests',
  'pandas',
  "ipykernel>=6.29.5",
]
